// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQWLBEC0OgoNiEIgVof5idEFjbBCazQtU',
    appId: '1:963214365060:android:80de487471d3b9fd1a8dd1',
    messagingSenderId: '963214365060',
    projectId: 'komandos-c184e',
    storageBucket: 'komandos-c184e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsVParFnDuGlCLl7Ty9Hw-xnCfP6LodhM',
    appId: '1:963214365060:ios:21c83db362a238ac1a8dd1',
    messagingSenderId: '963214365060',
    projectId: 'komandos-c184e',
    storageBucket: 'komandos-c184e.firebasestorage.app',
    androidClientId: '963214365060-1lukkdi4a0vtpqqbp20qvh1ab4jr754e.apps.googleusercontent.com',
    iosClientId: '963214365060-4idv7gmleen4n84iq5u0l37dbf8d3uao.apps.googleusercontent.com',
    iosBundleId: 'com.example.kbblRoutePlanner',
  );
}
